/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RDICT_H_RPCGEN
#define _RDICT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSTRING 255
#define MAXSTRING1 256
#define DICTSIZ 100

struct DictRecord {
	int longueur;
	char donnee[MAXSTRING1];
};
typedef struct DictRecord DictRecord;

#define RDICTPROG 0x30090949
#define RDICTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INITDICT 1
extern  int * initdict_1(void *, CLIENT *);
extern  int * initdict_1_svc(void *, struct svc_req *);
#define INSERTW 2
extern  int * insertw_1(DictRecord *, CLIENT *);
extern  int * insertw_1_svc(DictRecord *, struct svc_req *);
#define DELETEW 3
extern  int * deletew_1(DictRecord *, CLIENT *);
extern  int * deletew_1_svc(DictRecord *, struct svc_req *);
#define LOOKUPW 4
extern  int * lookupw_1(DictRecord *, CLIENT *);
extern  int * lookupw_1_svc(DictRecord *, struct svc_req *);
extern int rdictprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INITDICT 1
extern  int * initdict_1();
extern  int * initdict_1_svc();
#define INSERTW 2
extern  int * insertw_1();
extern  int * insertw_1_svc();
#define DELETEW 3
extern  int * deletew_1();
extern  int * deletew_1_svc();
#define LOOKUPW 4
extern  int * lookupw_1();
extern  int * lookupw_1_svc();
extern int rdictprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_DictRecord (XDR *, DictRecord*);

#else /* K&R C */
extern bool_t xdr_DictRecord ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RDICT_H_RPCGEN */
